### ISSUE TITLE
readme.md usage info is inaccurate

### ISSUE THREAD

**Issue by hazelnot** [adamkewley/fo2dat#1]
I tried to use the program, but the usage info in the readme lists commands that the actual executable throws errors about. Thankfully, the help flag worked fine.

**Comment by adamkewley** [comment]
Thanks for the feedback. I've just checked out `fo2dat` and executed each command in the `README.md` just fine. Maybe I'm misunderstanding, what kind of errors did you get? Where you running the commands exactly as written in the `README.md` (i.e. with a `$` prefixed, for example)?

**Comment by hazelnot** [comment]
I'm actually not sure what's going on, because I tried replicating it as well and it just worked flawlessly. Even the `--help` command is different now, matching the one in the readme. I'm extremely confused as to what happened. There is no other similarly named executable in the folder, so I have no idea how that could even have happened at all.

From looking at my terminal's history though I can see that I had to use `fo2dat --extract --file master.dat -C datfile` instead of `fo2dat -xf master.dat datfile`. Unfortunately there doesn't seem to be a way to see the PowerShell output from yesterday, unless I'm missing something.

**Comment by adamkewley** [comment]
Ah, it might've been that you checked out an older version of the software when I initially posted it on something like reddit (e.g. [here](https://www.reddit.com/r/rust/comments/8e3j46/fallout_2_dat2_archive_extractor_written_in_rust/) but I subsequently changed the CLI API.

I haven't touched this code in ages: for Fallout, I now tinker with [klamath](https://github.com/adamkewley/klamath), which is slowly growing a set of utilities for working with F1/2 files. Therefore, the API of fo2dat is unlikely to change in a hurry if you come to rely on it
